//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.19 at 04:49:50 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.bookong.net/schema/zest/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.bookong.zest.support.xml.data;
