//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.22 at 09:31:03 ���� CST 
//


package com.github.bookong.zest.support.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{https://www.bookong.net/schema/zest/data}RegExp"/>
 *           &lt;element ref="{https://www.bookong.net/schema/zest/data}CurrentTime"/>
 *           &lt;element ref="{https://www.bookong.net/schema/zest/data}FromCurrentTime"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Nullable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regExp",
    "currentTime",
    "fromCurrentTime"
})
@XmlRootElement(name = "Rule")
public class Rule {

    @XmlElement(name = "RegExp")
    protected String regExp;
    @XmlElement(name = "CurrentTime")
    protected CurrentTime currentTime;
    @XmlElement(name = "FromCurrentTime")
    protected FromCurrentTime fromCurrentTime;
    @XmlAttribute(name = "Path", required = true)
    protected String path;
    @XmlAttribute(name = "Nullable")
    protected Boolean nullable;

    /**
     * Gets the value of the regExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegExp() {
        return regExp;
    }

    /**
     * Sets the value of the regExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegExp(String value) {
        this.regExp = value;
    }

    /**
     * Gets the value of the currentTime property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentTime }
     *     
     */
    public CurrentTime getCurrentTime() {
        return currentTime;
    }

    /**
     * Sets the value of the currentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentTime }
     *     
     */
    public void setCurrentTime(CurrentTime value) {
        this.currentTime = value;
    }

    /**
     * Gets the value of the fromCurrentTime property.
     * 
     * @return
     *     possible object is
     *     {@link FromCurrentTime }
     *     
     */
    public FromCurrentTime getFromCurrentTime() {
        return fromCurrentTime;
    }

    /**
     * Sets the value of the fromCurrentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromCurrentTime }
     *     
     */
    public void setFromCurrentTime(FromCurrentTime value) {
        this.fromCurrentTime = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the nullable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNullable() {
        if (nullable == null) {
            return true;
        } else {
            return nullable;
        }
    }

    /**
     * Sets the value of the nullable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNullable(Boolean value) {
        this.nullable = value;
    }

}
