CREATE TABLE `tab1` (
  `id`            bigint       NOT NULL AUTO_INCREMENT,
  `v_tinyint`     tinyint          NULL ,
  `v_smallint`    smallint         NULL ,
  `v_mediumint`   mediumint        NULL ,
  `v_int`         int              NULL ,
  `v_integer`     integer          NULL ,
  `v_float`       float            NULL ,
  `v_double`      double           NULL ,
  `v_decimal`     decimal(4,2)     NULL ,
  `v_date`        date             NULL ,
  `v_time`        time             NULL ,
  `v_year`        year             NULL ,
  `v_datetime`    datetime         NULL ,
  `v_timestamp`   timestamp        NULL ,
  `v_char`        char(16)          NULL ,
  `v_varchar`     varchar(16)       NULL ,
  `v_tinyblob`    tinyblob         NULL ,
  `v_tinytext`    tinytext         NULL ,
  `v_blob`        blob             NULL ,
  `v_text`        text             NULL ,
  `v_mediumblob`  mediumblob       NULL ,
  `v_mediumtext`  mediumtext       NULL ,
  `v_longblob`    longblob         NULL ,
  `v_longtext`    longtext         NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tab1_u_1` (`v_varchar`)
) ;