//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.21 at 11:27:54 上午 CST 
//


package com.github.bookong.zest.core.xml.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.bookong.zest.core.xml.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Description_QNAME = new QName("https://www.bookong.net/schema/zest/data", "Description");
    private final static QName _RegExpRule_QNAME = new QName("https://www.bookong.net/schema/zest/data", "RegExpRule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.bookong.zest.core.xml.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParamField }
     * 
     */
    public ParamField createParamField() {
        return new ParamField();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link CurrentTimeRule }
     * 
     */
    public CurrentTimeRule createCurrentTimeRule() {
        return new CurrentTimeRule();
    }

    /**
     * Create an instance of {@link FromCurrentTimeRule }
     * 
     */
    public FromCurrentTimeRule createFromCurrentTimeRule() {
        return new FromCurrentTimeRule();
    }

    /**
     * Create an instance of {@link TestParam }
     * 
     */
    public TestParam createTestParam() {
        return new TestParam();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link DataSources }
     * 
     */
    public DataSources createDataSources() {
        return new DataSources();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Init }
     * 
     */
    public Init createInit() {
        return new Init();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.bookong.net/schema/zest/data", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.bookong.net/schema/zest/data", name = "RegExpRule")
    public JAXBElement<String> createRegExpRule(String value) {
        return new JAXBElement<String>(_RegExpRule_QNAME, String.class, null, value);
    }

}
